### ISSUE TITLE
Missing file Labels_Immoscout_HK_en.txt in the repository

### ISSUE THREAD

**Issue by Djoe1996** [Eyayaw/clean_RWI-GEO-RED#10]
Dear Eyayaw Beze,

I hope this message finds you well. I encountered an issue while running the script parse-labels_from_Stata-log-files.R.

The script attempts to access the file:
Dokumentation/Labels/Labels_Immoscout_HK_en.txt

However, this file seems to be missing in the repository. Could you please clarify:

Where can I obtain the file Labels_Immoscout_HK_en.txt?
Is there a specific process to generate this file?
Thank you for your time and support!

Best regards,

**Comment by eyayaw** [comment]
Hi @Djoe1996, 

Do you have access to the data? 

If so, you can find that file in the `Dokumentation/` directory, as shown in the code:
https://github.com/eyayaw/cleaning-RWI-GEO-RED/blob/ff7d4289cb46e0d974b33f8d113bbefe42cf645e/parse-labels_from_Stata-log-files.R#L88

If you don't, you can still find the generated labels in this repo.

**Comment by Djoe1996** [comment]
Hi @eyayaw 
Actually, I have access to the raw data. Would it be possible to send me the TXT file? I would be very grateful. I am currently working on my Bachelor's thesis, developing a Retrieval-Augmented Generation model, and cleaned data is crucial for ensuring the model provides accurate and non-hallucinatory answers.

**Comment by eyayaw** [comment]
If you have access to the data, it means you don't have the documentation. However, you should be able to get the labels from the provider. @PThie may help.

**Comment by Djoe1996** [comment]
thank you @eyayaw
