### ISSUE TITLE
What is the interpretation of age1?

### ISSUE THREAD

**Issue by Gutschlhofer** [Eyayaw/clean_RWI-GEO-RED#4]
^ the title. 

https://github.com/eyayaw/cleaning-RWI-GEO-RED/blob/62cfcea89814fee82470ca61ce145f490681cdbe/clean_rents.R#L361-L363

Why does the variable exist and how should we interpret it? 

My suggestion would be to construct a different `age1 = year - renov_year` which would reflect the time passed since the last renovation that definitely has some economic meaning since big renovations could come close to the feeling of a newer house.

**Comment by eyayaw** [comment]
That is a good point. My idea was that the speed of renovation may reveal something about the quality of the houses, shorter time indicating the house is not a good quality. However, I think your proposition sounds more plausible.
