### ISSUE TITLE
after in setcolorder(..., after = x) is not a feature of the function

### ISSUE THREAD

**Issue by Gutschlhofer** [Eyayaw/clean_RWI-GEO-RED#7]
Are you using a different version of data.table than the one on CRAN? Because the standard one does not allow for the parameter `after` in `setcolorder`. I suggest removing it, if you want to keep it you should make a note on the data.table fork you are using.

You use it in clean prices and rents:

https://github.com/eyayaw/cleaning-RWI-GEO-RED/blob/6fad94defe204b379e907079156f31bd0f69893b/clean_prices.R#L119

**Comment by eyayaw** [comment]
Sorry, yes, I use the development version of [data.table](https://github.com/Rdatatable/data.table) (v1.14.7). `setcolorder` in bulletpoint 25: https://github.com/Rdatatable/data.table/blob/cb8aeff9453acec878e5ab8515cda0d302c943eb/NEWS.md
